disabled_rules:

opt_in_rules:
  - statement_position
  - control_statement
  - private_action
  - private_outlet
  - prefixed_toplevel_constant
  - overridden_super_call
  - nesting
  - file_header
  - weak_delegate
  - trailing_semicolon
  - collection_alignment
  - empty_count
  - empty_string
  - fatal_error_message
  - function_default_parameter_at_end
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  # - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - override_in_extension
  - sorted_first_last
  - toggle_bool
  # - trailing_closure
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Pods

# custom rules

# adjusting rules

vertical_whitespace:
  max_empty_lines: 2

line_length: 
  ignores_comments: true
  warning: 190
  error: 200

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  (LearnLanguages.*?|Unit Tests)
                    \/\/
                    \/\/  (Created by .*? on .*?)
                    \/\/  Copyright © \d{4} Amir Khorsandi\. All rights reserved\.
                    \/\/
                   
type_name:
  excluded: id # excluded via string
identifier_name:
  excluded: 
    - to
    - at
reporter: "xcode"
