//
//  Youtube.swift
//  Learn Fluently
//
//  Created by Amir Khorsandi on 4/19/19.
//  Copyright © 2019 Amir Khorsandi. All rights reserved.
//

struct Youtube {

    struct VideoInfo {

        // MARK: Properties

        let title: String
        let videos: [VideoQuality]
        let captionURLs: [VideoCaption]
    }


    struct VideoQuality {

        // MARK: Properties

        let name: String
        let url: URL
    }


    struct VideoCaption {

        // MARK: Properties

        let languageName: String
        let languageCode: String
        let url: URL
        let isAutoGenerated: Bool


        // MARK: Static functions

        static func from(_ source: [AnyHashable: URL]?, isAutoGenerated: Bool = false) -> [VideoCaption] {
            return source?.map {
                let code = $0.key as? String ?? ""
                let name = (Locale.current as NSLocale).displayName(forKey: .identifier, value: code) ?? ""
                return VideoCaption(languageName: name,
                                    languageCode: code,
                                    url: $0.value,
                                    isAutoGenerated: isAutoGenerated)
            } ?? []
        }
    }

}
